workspace:
  base: /go/src
  path: github.com/PacketFire/immigrant

pipeline:
  build:
    image: ncatelli/golang:1.10.2-alpine3.7
    commands:
      - apk update ; apk add curl
      - curl https://glide.sh/get | sh
      - make

  docker:
    image: plugins/docker
    repo: packetfire/immigrant
    auto_tag: true
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
