workspace:
  base: /go/src
  path: github.com/ncatelli/immigrant

pipeline:
  test:
    image: ncatelli/golang:${GO_DOCKER_TAG}
    commands:
      - make test
  build:
    image: ncatelli/golang:${GO_DOCKER_TAG}
    commands:
      - make

matrix:
  GO_DOCKER_TAG: 
    - 1.9.6-alpine3.7
    - 1.10.2-alpine3.7
