workspace:
  base: /go/src
  path: github.com/ncatelli/immigrant

pipeline:
  fmt:
    image: ${GO_DOCKER_IMG} 
    commands:
      - make fmt
  test:
    image: ${GO_DOCKER_IMG}
    commands:
      - make test
  build:
    image: ${GO_DOCKER_IMG} 
    commands:
      - make

matrix:
  GO_DOCKER_IMG: ncatelli/golang:1.10.2-alpine:3.7
