version: '2'
services:
  mysql:
    image: mysql:5.7
    environment: 
      - MYSQL_ROOT_PASSWORD=password
  sqlite3:
    image: brockramz/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/